# Levity - OCPP Charge Point Management System
# Configuration file

server:
  address: ":8080"
  read_timeout: "30s"
  write_timeout: "30s"
  max_header_bytes: 1048576

database:
  path: "./levity.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

ocpp:
  heartbeat_interval: "60s"
  max_message_size: 1048576
  connection_timeout: "30s"

log:
  level: "info"
  format: "json"
  output: "stdout"
  add_source: true
  time_format: "2006-01-02T15:04:05.000Z07:00"

monitoring:
  enabled: true
  address: ":9090"
